import type { CapabilitySuggestion } from './types';

export const capabilityRegistry: CapabilitySuggestion[] = [
  {
    id: 'youtube.search_topic',
    label: 'Search YouTube for a topic',
    prompt: 'Search YouTube for a topic and compare the top results.',
    domain: 'browser',
    required: { site: 'youtube', pageType: 'home' },
    priority: 90,
  },
  {
    id: 'youtube.open_subscriptions',
    label: 'Summarize subscriptions',
    prompt: 'Open my subscriptions and summarize the most relevant recent uploads.',
    domain: 'browser',
    required: { site: 'youtube', pageType: 'home', signedIn: true },
    priority: 84,
  },
  {
    id: 'youtube.channel_analysis',
    label: 'Analyze a channel',
    prompt: 'Open a channel and summarize what it has posted recently.',
    domain: 'browser',
    required: { site: 'youtube', pageType: 'home' },
    priority: 80,
  },
  {
    id: 'youtube.upload_video',
    label: 'Upload a video',
    prompt: 'Start the upload flow for a video and help me fill it out.',
    domain: 'browser',
    required: { site: 'youtube', pageType: 'home', signedIn: true },
    priority: 78,
  },
  {
    id: 'youtube.extract_transcript',
    label: 'Extract video transcript',
    prompt: 'Extract the transcript from this video.',
    domain: 'browser',
    required: { site: 'youtube', pageType: 'video' },
    priority: 100,
    tags: ['video'],
  },
  {
    id: 'youtube.summarize_video',
    label: 'Summarize this video',
    prompt: 'Summarize this video and list the key takeaways.',
    domain: 'browser',
    required: { site: 'youtube', pageType: 'video' },
    priority: 96,
    tags: ['video'],
  },
  {
    id: 'youtube.timestamps',
    label: 'Pull key timestamps',
    prompt: 'Pull out the important timestamps and key moments from this video.',
    domain: 'browser',
    required: { site: 'youtube', pageType: 'video' },
    priority: 92,
    tags: ['video'],
  },
  {
    id: 'youtube.open_channel_from_video',
    label: 'Analyze the creator',
    prompt: 'Open this creator channel and analyze recent upload patterns.',
    domain: 'browser',
    required: { site: 'youtube', pageType: 'video' },
    priority: 82,
    tags: ['video'],
  },
  {
    id: 'gmail.summarize_inbox',
    label: 'Summarize inbox',
    prompt: 'Summarize the most important emails in my inbox.',
    domain: 'browser',
    required: { site: 'gmail', pageType: 'inbox', signedIn: true },
    priority: 100,
  },
  {
    id: 'gmail.find_invoices',
    label: 'Find invoices',
    prompt: 'Find invoice or receipt emails from this month and summarize them.',
    domain: 'browser',
    required: { site: 'gmail', signedIn: true },
    priority: 90,
  },
  {
    id: 'gmail.draft_reply',
    label: 'Draft a reply',
    prompt: 'Draft a reply to the currently selected email.',
    domain: 'browser',
    required: { site: 'gmail', pageType: 'thread', signedIn: true },
    priority: 88,
  },
  {
    id: 'repo.run_tests',
    label: 'Run tests and summarize failures',
    prompt: 'Run the tests in this repo and summarize what is failing.',
    domain: 'terminal',
    required: { repoOpen: true },
    priority: 100,
  },
  {
    id: 'repo.find_bug_source',
    label: 'Trace a bug',
    prompt: 'Trace the source of a bug in this codebase and explain the cause.',
    domain: 'terminal',
    required: { repoOpen: true },
    priority: 94,
  },
  {
    id: 'repo.architecture_summary',
    label: 'Summarize architecture',
    prompt: 'Summarize the architecture of this codebase.',
    domain: 'terminal',
    required: { repoOpen: true },
    priority: 80,
  },
  {
    id: 'repo.fix_failing_tests',
    label: 'Fix failing tests',
    prompt: 'Run the failing tests, fix the issue, and explain the change.',
    domain: 'terminal',
    required: { repoOpen: true },
    priority: 96,
  },
  {
    id: 'files.summarize_folder',
    label: 'Summarize this folder',
    prompt: 'Summarize what is in this folder and what each item is for.',
    domain: 'filesystem',
    required: { domain: 'filesystem' },
    priority: 82,
  },
  {
    id: 'files.find_relevant_doc',
    label: 'Find the right file',
    prompt: 'Find the most relevant file for this task and open it.',
    domain: 'filesystem',
    required: { domain: 'filesystem' },
    priority: 86,
  },
  {
    id: 'desktop.summarize_current_app',
    label: 'Explain what is on screen',
    prompt: 'Summarize what is currently visible in this app and what I can do next.',
    domain: 'desktop',
    required: { domain: 'desktop' },
    priority: 80,
  },
  {
    id: 'desktop.find_settings',
    label: 'Find the right setting',
    prompt: 'Find the setting I need in this app and change it.',
    domain: 'desktop',
    required: { domain: 'desktop' },
    priority: 78,
  },
];
