// src/main/core/cli/cdpTools.ts
// CDP-powered browser tools that leverage the Chrome DevTools Protocol debugger
// for capabilities beyond what executeJavaScript can provide.
import type Anthropic from '@anthropic-ai/sdk';
import type { ElectronBrowserService } from '../browser/ElectronBrowserService';

export const CDP_TOOLS: Anthropic.Tool[] = [
  // ── Input Domain ──────────────────────────────────────────────────────────────
  {
    name: 'browser_cdp_mouse',
    description:
      'Dispatch a low-level compositor mouse event via CDP Input.dispatchMouseEvent. ' +
      'These are indistinguishable from physical mouse input — they trigger CSS :hover/:active, ' +
      'all event listeners, and work across all JS frameworks. Use for precise coordinate-based ' +
      'clicking, dragging, or hover when CSS selectors are unreliable.',
    input_schema: {
      type: 'object' as const,
      properties: {
        type: {
          type: 'string',
          enum: ['mousePressed', 'mouseReleased', 'mouseMoved', 'mouseWheel'],
          description: 'Mouse event type',
        },
        x: { type: 'number', description: 'X coordinate relative to viewport' },
        y: { type: 'number', description: 'Y coordinate relative to viewport' },
        button: { type: 'string', enum: ['left', 'right', 'middle'], description: 'Mouse button (default: left)' },
        clickCount: { type: 'number', description: 'Click count for double/triple click (default: 1)' },
        deltaX: { type: 'number', description: 'Horizontal scroll delta for mouseWheel' },
        deltaY: { type: 'number', description: 'Vertical scroll delta for mouseWheel' },
        modifiers: { type: 'number', description: 'Bit flags: 1=Alt, 2=Ctrl, 4=Meta, 8=Shift' },
      },
      required: ['type', 'x', 'y'],
    },
  },
  {
    name: 'browser_cdp_key',
    description:
      'Dispatch a low-level key event via CDP Input.dispatchKeyEvent. ' +
      'These generate real keyboard events indistinguishable from physical input. ' +
      'For typing text, send a "char" event for each character. For special keys, ' +
      'send "keyDown" then "keyUp" with the appropriate key code.',
    input_schema: {
      type: 'object' as const,
      properties: {
        type: { type: 'string', enum: ['keyDown', 'keyUp', 'rawKeyDown', 'char'], description: 'Key event type' },
        key: { type: 'string', description: 'Key value (e.g. "a", "Enter", "Tab", "ArrowDown")' },
        code: { type: 'string', description: 'Physical key code (e.g. "KeyA", "Enter", "Tab")' },
        text: { type: 'string', description: 'Text generated by the key (for char events)' },
        modifiers: { type: 'number', description: 'Bit flags: 1=Alt, 2=Ctrl, 4=Meta, 8=Shift' },
        windowsVirtualKeyCode: { type: 'number', description: 'Windows virtual key code (e.g. 13 for Enter, 9 for Tab)' },
      },
      required: ['type', 'key'],
    },
  },
  {
    name: 'browser_cdp_touch',
    description:
      'Dispatch a touch event via CDP Input.dispatchTouchEvent for touch simulation.',
    input_schema: {
      type: 'object' as const,
      properties: {
        type: { type: 'string', enum: ['touchStart', 'touchEnd', 'touchMove', 'touchCancel'], description: 'Touch event type' },
        touchPoints: {
          type: 'array',
          description: 'Array of touch points',
          items: {
            type: 'object',
            properties: {
              x: { type: 'number' },
              y: { type: 'number' },
              id: { type: 'number' },
              radiusX: { type: 'number' },
              radiusY: { type: 'number' },
              force: { type: 'number' },
            },
            required: ['x', 'y'],
          },
        },
      },
      required: ['type', 'touchPoints'],
    },
  },

  // ── Fetch / Network Domain ────────────────────────────────────────────────────
  {
    name: 'browser_cdp_fetch_enable',
    description:
      'Enable request interception via CDP Fetch domain. Once enabled, matching requests pause ' +
      'and can be continued, fulfilled with synthetic responses, or failed. Use patterns to filter ' +
      'by URL glob or resource type. Call browser_cdp_fetch_disable to stop intercepting.',
    input_schema: {
      type: 'object' as const,
      properties: {
        patterns: {
          type: 'array',
          description: 'Request patterns to intercept. Empty array = intercept all.',
          items: {
            type: 'object',
            properties: {
              urlPattern: { type: 'string', description: 'URL glob pattern (e.g. "*.js", "https://api.example.com/*")' },
              resourceType: { type: 'string', description: 'Resource type filter (Document, Script, Stylesheet, Image, XHR, Fetch, etc.)' },
              requestStage: { type: 'string', enum: ['Request', 'Response'], description: 'Stage to intercept (default: Request)' },
            },
          },
        },
      },
    },
  },
  {
    name: 'browser_cdp_fetch_disable',
    description: 'Disable request interception. Stops pausing requests.',
    input_schema: { type: 'object' as const, properties: {} },
  },
  {
    name: 'browser_cdp_fetch_continue',
    description:
      'Continue an intercepted request, optionally modifying URL, method, headers, or POST data.',
    input_schema: {
      type: 'object' as const,
      properties: {
        requestId: { type: 'string', description: 'The paused request ID (from Fetch.requestPaused event)' },
        url: { type: 'string', description: 'Override URL' },
        method: { type: 'string', description: 'Override HTTP method' },
        headers: {
          type: 'array',
          description: 'Override headers',
          items: {
            type: 'object',
            properties: {
              name: { type: 'string' },
              value: { type: 'string' },
            },
            required: ['name', 'value'],
          },
        },
        postData: { type: 'string', description: 'Override POST body' },
      },
      required: ['requestId'],
    },
  },
  {
    name: 'browser_cdp_fetch_fulfill',
    description:
      'Fulfill an intercepted request with a synthetic response. Returns the given body and status ' +
      'to the page without hitting the network. Use for mocking APIs, blocking ads, injecting content.',
    input_schema: {
      type: 'object' as const,
      properties: {
        requestId: { type: 'string', description: 'The paused request ID' },
        responseCode: { type: 'number', description: 'HTTP status code (e.g. 200, 404, 302)' },
        body: { type: 'string', description: 'Response body text' },
        headers: {
          type: 'array',
          description: 'Response headers',
          items: {
            type: 'object',
            properties: {
              name: { type: 'string' },
              value: { type: 'string' },
            },
            required: ['name', 'value'],
          },
        },
      },
      required: ['requestId', 'responseCode'],
    },
  },
  {
    name: 'browser_cdp_fetch_fail',
    description: 'Fail an intercepted request with a network error.',
    input_schema: {
      type: 'object' as const,
      properties: {
        requestId: { type: 'string', description: 'The paused request ID' },
        reason: {
          type: 'string',
          description: 'Error reason: Failed, Aborted, TimedOut, AccessDenied, ConnectionClosed, ConnectionReset, ConnectionRefused, ConnectionAborted, ConnectionFailed, NameNotResolved, InternetDisconnected, AddressUnreachable, BlockedByClient, BlockedByResponse',
        },
      },
      required: ['requestId', 'reason'],
    },
  },
  {
    name: 'browser_cdp_cookies_get',
    description: 'Get all cookies, optionally filtered by URLs.',
    input_schema: {
      type: 'object' as const,
      properties: {
        urls: {
          type: 'array',
          description: 'Filter cookies by these URLs (optional — omit for all cookies)',
          items: { type: 'string' },
        },
      },
    },
  },
  {
    name: 'browser_cdp_cookies_set',
    description: 'Set a cookie.',
    input_schema: {
      type: 'object' as const,
      properties: {
        name: { type: 'string' },
        value: { type: 'string' },
        domain: { type: 'string' },
        path: { type: 'string' },
        secure: { type: 'boolean' },
        httpOnly: { type: 'boolean' },
        sameSite: { type: 'string', enum: ['Strict', 'Lax', 'None'] },
        url: { type: 'string', description: 'URL to associate the cookie with (alternative to domain)' },
        expires: { type: 'number', description: 'Unix timestamp for expiration' },
      },
      required: ['name', 'value'],
    },
  },
  {
    name: 'browser_cdp_cookies_delete',
    description: 'Delete cookies matching the given filter.',
    input_schema: {
      type: 'object' as const,
      properties: {
        name: { type: 'string', description: 'Cookie name to delete' },
        domain: { type: 'string' },
        path: { type: 'string' },
        url: { type: 'string' },
      },
      required: ['name'],
    },
  },
  {
    name: 'browser_cdp_network_emulate',
    description:
      'Emulate network conditions: throttle bandwidth, add latency, or go offline. ' +
      'Use to test slow connections or simulate network failures.',
    input_schema: {
      type: 'object' as const,
      properties: {
        offline: { type: 'boolean', description: 'Simulate offline (default: false)' },
        latency: { type: 'number', description: 'Additional latency in ms (default: 0)' },
        downloadThroughput: { type: 'number', description: 'Download speed in bytes/sec (-1 = unlimited)' },
        uploadThroughput: { type: 'number', description: 'Upload speed in bytes/sec (-1 = unlimited)' },
      },
    },
  },

  // ── Accessibility + DOMSnapshot ───────────────────────────────────────────────
  {
    name: 'browser_cdp_accessibility_tree',
    description:
      'Get the full accessibility tree for the page via CDP Accessibility.getFullAXTree. ' +
      'Returns every node with role, name, value, description, states (focused, disabled, checked, etc.), ' +
      'and relationships. Far more robust than CSS selectors for understanding page structure.',
    input_schema: { type: 'object' as const, properties: {} },
  },
  {
    name: 'browser_cdp_accessibility_query',
    description:
      'Search the accessibility tree by role and/or name. Returns matching nodes. ' +
      'Use to find elements by their semantic meaning (e.g. role="button" name="Submit").',
    input_schema: {
      type: 'object' as const,
      properties: {
        role: { type: 'string', description: 'ARIA role to search for (e.g. "button", "textbox", "link", "heading")' },
        name: { type: 'string', description: 'Accessible name to search for (e.g. "Submit", "Search")' },
      },
    },
  },
  {
    name: 'browser_cdp_dom_snapshot',
    description:
      'Capture a complete DOM + CSS + layout snapshot in one call via DOMSnapshot.captureSnapshot. ' +
      'Returns the entire document structure with computed styles, layout metrics, and text content. ' +
      'Excellent for comprehensive page analysis without multiple queries.',
    input_schema: {
      type: 'object' as const,
      properties: {
        computedStyles: {
          type: 'array',
          description: 'CSS properties to include in snapshot (default: display, visibility, opacity, color, font-size, background-color)',
          items: { type: 'string' },
        },
      },
    },
  },

  // ── Emulation Domain ──────────────────────────────────────────────────────────
  {
    name: 'browser_cdp_emulate_device',
    description: 'Override device metrics: viewport size, scale factor, mobile flag. Use for responsive testing or mobile site access.',
    input_schema: {
      type: 'object' as const,
      properties: {
        width: { type: 'number', description: 'Viewport width' },
        height: { type: 'number', description: 'Viewport height' },
        deviceScaleFactor: { type: 'number', description: 'Device pixel ratio (default: 1)' },
        mobile: { type: 'boolean', description: 'Emulate mobile (default: false)' },
      },
      required: ['width', 'height'],
    },
  },
  {
    name: 'browser_cdp_emulate_geolocation',
    description: 'Override geolocation to spoof GPS coordinates.',
    input_schema: {
      type: 'object' as const,
      properties: {
        latitude: { type: 'number' },
        longitude: { type: 'number' },
        accuracy: { type: 'number', description: 'Accuracy in meters (default: 100)' },
      },
      required: ['latitude', 'longitude'],
    },
  },
  {
    name: 'browser_cdp_emulate_timezone',
    description: 'Override the browser timezone (e.g. "America/New_York", "Europe/London").',
    input_schema: {
      type: 'object' as const,
      properties: {
        timezoneId: { type: 'string', description: 'IANA timezone ID' },
      },
      required: ['timezoneId'],
    },
  },

  // ── Page Domain extras ────────────────────────────────────────────────────────
  {
    name: 'browser_cdp_print_pdf',
    description: 'Generate a PDF of the current page. Returns base64-encoded PDF data.',
    input_schema: {
      type: 'object' as const,
      properties: {
        landscape: { type: 'boolean', description: 'Landscape orientation (default: false)' },
        printBackground: { type: 'boolean', description: 'Print background graphics (default: true)' },
        scale: { type: 'number', description: 'Scale factor (default: 1)' },
        paperWidth: { type: 'number', description: 'Paper width in inches (default: 8.5)' },
        paperHeight: { type: 'number', description: 'Paper height in inches (default: 11)' },
      },
    },
  },
  {
    name: 'browser_cdp_file_chooser',
    description:
      'Control file chooser interception. First call with action="intercept" to start intercepting, ' +
      'then when a file chooser appears call with action="accept" and files array, or action="cancel".',
    input_schema: {
      type: 'object' as const,
      properties: {
        action: { type: 'string', enum: ['intercept', 'accept', 'cancel', 'stop'], description: 'intercept=start intercepting, accept=select files, cancel=dismiss, stop=stop intercepting' },
        files: {
          type: 'array',
          description: 'File paths to select (for accept action)',
          items: { type: 'string' },
        },
      },
      required: ['action'],
    },
  },
  {
    name: 'browser_cdp_handle_dialog',
    description: 'Handle a JavaScript alert/confirm/prompt dialog. Accept or dismiss it, optionally providing text for prompt dialogs.',
    input_schema: {
      type: 'object' as const,
      properties: {
        accept: { type: 'boolean', description: 'Accept (true) or dismiss (false) the dialog' },
        promptText: { type: 'string', description: 'Text to enter for prompt dialogs' },
      },
      required: ['accept'],
    },
  },

  // ── Storage Domain ────────────────────────────────────────────────────────────
  {
    name: 'browser_cdp_storage_get',
    description: 'Get all localStorage or sessionStorage items for an origin.',
    input_schema: {
      type: 'object' as const,
      properties: {
        origin: { type: 'string', description: 'Security origin (e.g. "https://example.com")' },
        isLocalStorage: { type: 'boolean', description: 'true=localStorage, false=sessionStorage (default: true)' },
      },
      required: ['origin'],
    },
  },
  {
    name: 'browser_cdp_storage_set',
    description: 'Set a localStorage or sessionStorage item for an origin.',
    input_schema: {
      type: 'object' as const,
      properties: {
        origin: { type: 'string', description: 'Security origin' },
        isLocalStorage: { type: 'boolean', description: 'true=localStorage, false=sessionStorage (default: true)' },
        key: { type: 'string' },
        value: { type: 'string' },
      },
      required: ['origin', 'key', 'value'],
    },
  },
  {
    name: 'browser_cdp_storage_clear',
    description: 'Clear all storage data for an origin (cookies, localStorage, sessionStorage, cache, IndexedDB, etc.).',
    input_schema: {
      type: 'object' as const,
      properties: {
        origin: { type: 'string', description: 'Security origin' },
        storageTypes: { type: 'string', description: 'Comma-separated types: cookies, file_systems, indexeddb, local_storage, shader_cache, websql, service_workers, cache_storage, all (default: all)' },
      },
      required: ['origin'],
    },
  },
];

export type CDPToolInput = Record<string, unknown>;

/**
 * Execute a CDP tool call on a conversation-scoped tab.
 */
export async function executeCDPTool(
  name: string,
  input: CDPToolInput,
  browser: ElectronBrowserService,
  tabId: string,
): Promise<unknown> {
  switch (name) {
    // ── Input ──
    case 'browser_cdp_mouse': {
      await browser.cdpMouseEventOnTab(tabId, input.type as any, input.x as number, input.y as number, {
        button: input.button as any,
        clickCount: input.clickCount as number,
        deltaX: input.deltaX as number,
        deltaY: input.deltaY as number,
        modifiers: input.modifiers as number,
      });
      return { ok: true };
    }
    case 'browser_cdp_key': {
      await browser.cdpKeyEventOnTab(tabId, input.type as any, input.key as string, {
        code: input.code as string,
        text: input.text as string,
        modifiers: input.modifiers as number,
        windowsVirtualKeyCode: input.windowsVirtualKeyCode as number,
      });
      return { ok: true };
    }
    case 'browser_cdp_touch': {
      await browser.cdpTouchEventOnTab(tabId, input.type as any, input.touchPoints as any[]);
      return { ok: true };
    }

    // ── Fetch / Network ──
    case 'browser_cdp_fetch_enable': {
      await browser.cdpFetchEnableOnTab(tabId, input.patterns as any[]);
      return { ok: true, message: 'Request interception enabled' };
    }
    case 'browser_cdp_fetch_disable': {
      await browser.cdpFetchDisableOnTab(tabId);
      return { ok: true, message: 'Request interception disabled' };
    }
    case 'browser_cdp_fetch_continue': {
      const { requestId, ...overrides } = input;
      await browser.cdpFetchContinueOnTab(tabId, requestId as string, overrides as any);
      return { ok: true };
    }
    case 'browser_cdp_fetch_fulfill': {
      await browser.cdpFetchFulfillOnTab(
        tabId,
        input.requestId as string,
        input.responseCode as number,
        input.body as string | undefined,
        input.headers as any,
      );
      return { ok: true };
    }
    case 'browser_cdp_fetch_fail': {
      await browser.cdpFetchFailOnTab(tabId, input.requestId as string, input.reason as string);
      return { ok: true };
    }
    case 'browser_cdp_cookies_get': {
      const cookies = await browser.cdpGetCookiesOnTab(tabId, input.urls as string[] | undefined);
      return { ok: true, cookies };
    }
    case 'browser_cdp_cookies_set': {
      const success = await browser.cdpSetCookieOnTab(tabId, input as any);
      return { ok: true, success };
    }
    case 'browser_cdp_cookies_delete': {
      await browser.cdpDeleteCookiesOnTab(tabId, input as any);
      return { ok: true };
    }
    case 'browser_cdp_network_emulate': {
      await browser.cdpEmulateNetworkOnTab(tabId, input as any);
      return { ok: true };
    }

    // ── Accessibility + DOMSnapshot ──
    case 'browser_cdp_accessibility_tree': {
      const tree = await browser.cdpGetAccessibilityTreeOnTab(tabId);
      return { ok: true, data: tree };
    }
    case 'browser_cdp_accessibility_query': {
      const result = await browser.cdpQueryAccessibilityOnTab(tabId, {
        role: input.role as string,
        name: input.name as string,
      });
      return { ok: true, data: result };
    }
    case 'browser_cdp_dom_snapshot': {
      const snapshot = await browser.cdpDOMSnapshotOnTab(tabId, {
        computedStyles: input.computedStyles as string[],
      });
      return { ok: true, data: snapshot };
    }

    // ── Emulation ──
    case 'browser_cdp_emulate_device': {
      await browser.cdpSetDeviceMetricsOnTab(tabId, input as any);
      return { ok: true };
    }
    case 'browser_cdp_emulate_geolocation': {
      await browser.cdpSetGeolocationOnTab(tabId, input.latitude as number, input.longitude as number, input.accuracy as number);
      return { ok: true };
    }
    case 'browser_cdp_emulate_timezone': {
      await browser.cdpSetTimezoneOnTab(tabId, input.timezoneId as string);
      return { ok: true };
    }

    // ── Page extras ──
    case 'browser_cdp_print_pdf': {
      const pdf = await browser.cdpPrintToPDFOnTab(tabId, input as any);
      return { ok: true, data: pdf.data, mimeType: 'application/pdf', encoding: 'base64' };
    }
    case 'browser_cdp_file_chooser': {
      const action = input.action as string;
      if (action === 'intercept') {
        await browser.cdpSetFileChooserInterceptOnTab(tabId, true);
        return { ok: true, message: 'File chooser interception started' };
      } else if (action === 'stop') {
        await browser.cdpSetFileChooserInterceptOnTab(tabId, false);
        return { ok: true, message: 'File chooser interception stopped' };
      } else {
        await browser.cdpHandleFileChooserOnTab(tabId, action as any, input.files as string[]);
        return { ok: true };
      }
    }
    case 'browser_cdp_handle_dialog': {
      await browser.cdpHandleDialogOnTab(tabId, input.accept as boolean, input.promptText as string);
      return { ok: true };
    }

    // ── Storage ──
    case 'browser_cdp_storage_get': {
      const entries = await browser.cdpGetStorageOnTab(tabId, input.origin as string, input.isLocalStorage !== false);
      return { ok: true, entries };
    }
    case 'browser_cdp_storage_set': {
      await browser.cdpSetStorageItemOnTab(tabId, input.origin as string, input.isLocalStorage !== false, input.key as string, input.value as string);
      return { ok: true };
    }
    case 'browser_cdp_storage_clear': {
      await browser.cdpClearStorageOnTab(tabId, input.origin as string, input.storageTypes as string);
      return { ok: true };
    }

    default:
      return { ok: false, error: `Unknown CDP tool: ${name}` };
  }
}
